### ISSUE TITLE
Odd and unknown ID throws error in "create-students-file" command

### ISSUE THREAD

**Issue by htdebeer-tue** [htdebeer-tue/repobee-canvas#13]
Lars reported an error when he runs:

```
repobee canvas create-students-file   --canvas-assignment-id 62739 --canvas-git-map canvas-git-map.csv   --canvas-students-file canvas-students-file-HA0.lst 
```

The error:

```
[ERROR] Canvas ID '844bb179ed55664e5ccad7dcb2d31a62b1d81042' not mapped to a Git ID.
[ERROR] Critical exception
Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/main.py", line 171, in _main
    _repobee.cli.dispatch.dispatch_command(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/cli/dispatch.py", line 48, in dispatch_command
    else ext_cmd.command()
  File "/media/data/repobee-canvas/repobee_canvas/command/create_students_file.py", line 90, in command
    create_students_file(assignment, canvas_git_mapping_table, Path(self.canvas_students_file))
  File "/media/data/repobee-canvas/repobee_canvas/command/create_students_file.py", line 111, in create_students_file
    git_id      = canvas_git_mapping_table.canvas2git(canvas_id)
  File "/media/data/repobee-canvas/repobee_canvas/canvas_git_map.py", line 112, in canvas2git
    raise ValueError(f"Canvas ID '{canvas_id}' not mapped to a Git ID.")
ValueError: Canvas ID '844bb179ed55664e5ccad7dcb2d31a62b1d81042' not mapped to a Git ID.
```

Looking at the list of accounts, we have one teacher who has also a student account. It is possible that Canvas generates this odd account ID "844bb179ed55664e5ccad7dcb2d31a62b1d81042" for this teacher-acting-student. If so, add support for this when generating the Canvas Git mapping table.

**Comment by htdebeer-tue** [comment]
After adding the teacher also as a student to one of my testing courses, I was unable to reproduce the issue. I will investigate further.

**Comment by htdebeer-tue** [comment]
I can reproduce the issue on the TU/e test Canvas server.

**Comment by htdebeer-tue** [comment]
It is the test student. This is odd, because I filter it out. Or at least, I tried. Apparently, in this course, the test student is named "Test student", whereas I saw only test students named "Test Student" before. I can make this more robust by checking for "test student" in any form in the user's name.
